### ISSUE TITLE
[FRONT-END] Recuperar dados do endpoint para o card "Programa de lavagem de mãos"

### ISSUE THREAD

**Issue by mfreireunicef** [UNICEF01/Paineis-do-Selo#133]

**Comment by mfreireunicef** [comment]
Com base numa segunda demanda semelhante estimada, confirmei que essa demanda levou aproxidamente 1h para ser feita.

**Comment by mfreireunicef** [comment]
@gucostaunicef @lucasferreiraunicef A parte da porcentagem desse card eu nao consegui entender a regra e não indentifiquei no endpoint, retiro do card? Ou mantenho statico (0%)?

endpoint: https://api.paineis.testes.selounicef.org.br/api/docs#/Systemic%20Results/getHygieneHabits

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef Para este card, considere excluir a progress bar. Não faz sentido para a atividade em questão.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Obrigado.
