### ISSUE TITLE
[ALTERACÃO PRAZOS] 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#191]
**RS 3 - Formação** 
**Prazo: 31 de dezembro de 2022**
![Captura de Tela 2022-07-20 às 11.45.02.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/8134e185-54bd-4124-a7ba-5fc6c43fb773)

______________________________________________________

**RS 4 - Estágio, aprendizagem e trabalho**
**Prazo: 30 de junho de 2024.**
![Captura de Tela 2022-07-20 às 11.49.42.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/1e282476-8f0f-4190-9f47-12935eca2655)

_______________________________________________________

**RS 5 - Fluxo de atendimento** 
**Prazo: 31 de agosto de 2022**
![Captura de Tela 2022-07-20 às 11.55.37.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/abafd73a-8a94-4d1d-9411-5aa61f41eb41)

_______________________________________________________

**Comment by lucasferreiraunicef** [comment]
@fialalucas @mfreireunicef @gucostaunicef

**Comment by mfreireunicef** [comment]
@fialalucas @gucostaunicef Alteração feita no front
