### ISSUE TITLE
[ALTERAR LAYOUT] RS E PCGR

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#212]
![Captura de Tela 2022-07-21 às 15.07.23.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/c981c9bc-4d7b-4578-92f9-94d22dd32c7c)

Tela de Referencia:

[Link](https://xd.adobe.com/view/f6057092-e218-47ab-986c-6903c7b500f7-a356/)

**Comment by lucasferreiraunicef** [comment]
@fialalucas gentileza postar o link

**Comment by fialalucas** [comment]
https://xd.adobe.com/view/580aa501-fbad-4107-98ff-dc4447911b61-0d59/
