### ISSUE TITLE
[ADICIONAR] LINK ATIVIDADES

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#286]
Descrição: Adicionar os seguintes itens abaixo

![Captura de Tela 2022-09-12 às 14.38.11.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/5a9d0e33-9196-4fea-9ebc-dc023949855b)
 

Lista:

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

Estão faltando alguns itens, porém, aqueles que ja estão prontos, podemos inserir no painel.

Acesse a Coluna "LINK"

[Planilha](https://unicef-my.sharepoint.com/:x:/g/personal/lfiala_unicef_org/EeaGuHlsjmZNheDYmdjyjJABu5fQog3VrHMtlNZT_0E4Cg?wdOrigin=TEAMS-WEB.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1663262917171)

**Comment by mfreireunicef** [comment]
![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/c545f7cd-4b5f-4f69-8b6f-7a798626c79e)

@lucasferreiraunicef estou sem acesso...
