### ISSUE TITLE
[INDICADOR SOCIAL 1] Eu como Município, Desejo  acompanhar o percentual de crianças de 1 ano vacinadas com a vacina tríplice viral (D2) e tetra viral.

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#299]
**Descrição:** Percentual de crianças de 1 ano vacinadas com a vacina tríplice viral (D2) e tetra viral.

**Regras de Pontuação (Atividade):**
**LINHA DE BASE: 2020.**

A meta(TARGET) para este INDICADOR Social será de 95% e os demais devemos considerar o TARGET do primeiro ano que for recuperado.

EXEMPLO:
![Captura de Tela 2022-09-27 às 15.13.28.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/905c020b-8f19-4c0d-8fe0-41d2aad636db)

1 - O município pontua 2 pontos atingir a **meta(Target)** durante os anos e manter até o final do SELO.

Essa verificacão deverá ser feita com base no ano superior a linha de base.

2 - O município pontua 1 ponto se o mesmo manteve ou melhorou o **value** se comparado com o **value** do **ano de BASE (2020)**

![Captura de Tela 2022-09-27 às 10.21.57.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/84a8191b-710b-4661-ba1c-a92277f5ce00)

3 - O município não pontua (0) se ao final do SELO o mesmo piorou o **value** se comparado com o **value do ano de BASE (2020)**

![Captura de Tela 2022-09-27 às 10.21.57.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/84a8191b-710b-4661-ba1c-a92277f5ce00)

________________________________________________________________________________________________

**Regra de Status:** 

**Durante ->**
Desenvolvimento está positivo
Indicador abaixo da meta
Indicador está Piorando

**Conclusão do Selo - >** 
Meta Atingida com sucesso
Indicador se manteve estável
Indicador piorou

Obs: Caso não exista o dado do ano vigente e de qualquer ano, o gráfico e os status devem ser mantidos de acordo com o dado do último ano que se tenha os dados consolidados.

_______________________________________________________________________________________________

[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

[Responsivo - referência ](https://xd.adobe.com/view/76552a63-5b38-4b0e-ae70-2f192c288a36-2306/specs/)

[Protótipo IS](https://xd.adobe.com/view/76552a63-5b38-4b0e-ae70-2f192c288a36-2306/specs/)

[Endpoint](https://sdmx.data.unicef.org/ws/public/sdmxapi/rest/data/BRAZIL_CO,BRAZIL_CO_SELO,1.0/4125902.PERC_ESCOLAS_AGUA_ADQ...?format=sdmx-json) 

DataFlow:
[Link](https://sdmx.data.unicef.org/webservice/data.html)

Endpoint Detalhado: https://sdmx.data.unicef.org/ws/public/sdmxapi/rest/data/BRAZIL_CO,BRAZIL_CO_SELO,1.0/4125902.PERC_ESCOLAS_AGUA_ADQ...?format=sdmx-json

![Captura de Tela 2022-09-27 às 10.11.54.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/694552f8-264a-42ec-9635-906c9d149bc4)

**Comment by mfreireunicef** [comment]
Segundo @fialalucas a regra das **cores** e **textos** dos cards da tela é:

**Data Limite da tela: 30/06/2024**

**2 pontos** (antes da data limite) = **cor**: AZUL | **Texto**: O município de Coari (AM) vem melhorando esse indicador desde o início da participação do SELO UNICEF.
**1 ponto** (antes da data limite) =  **cor**: AMARELO | **Texto**: O município de Coari (AM) ainda não atingiu a meta estipulada pelo SELO UNICEF
**0 ponto** (antes da data limite) = **cor**: LARANJA | **Texto**: O município de Coari (AM) está regredindo seu desenvolvimento neste indicador até o momento analisado.


**2 pontos** (depois da data limite) = **cor**: AZUL | **Texto**: O município de Coari (AM) obteve sucesso neste indicador analisado pelo SELO UNICEF.
**1 ponto** (depois da data limite) =  **cor**: AMARELO | **Texto**: O município de Coari (AM) manteve o indicador abaixo da meta estipulada pelo SELO UNICEF
**0 ponto** (depois da data limite) = **cor**: VERMELHO | **Texto**: O município de Coari (AM) regrediu seu desenvolvimento neste indicador.

**Comment by fialalucas** [comment]
Perfeito
