### ISSUE TITLE
[ALTERACÃO INDICADOR SOCIAL] Alterar a "Pontuacão IS"

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#339]
**01 ) A pontuacão deverá aparecer no CARD somente ao final do SELO (01/07/2024).**
![Captura de Tela 2022-10-13 às 10.05.56.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/250a5cf5-cf45-4960-87fd-fc0c5c20de26)

**Comment by mfreireunicef** [comment]
Necessario retorno da "flag" do backend para dinamizar se vai ou não aparecer o componernete de "pontos" dentro dos cards.
