### ISSUE TITLE
[FRONT-END] Implementar botão e adequar ao responsivo da pagina

### ISSUE THREAD

**Issue by mfreireunicef** [UNICEF01/Paineis-do-Selo#410]
@fialalucas Por favor, informar quando finalizar o novo prototipo do botão.

**Comment by fialalucas** [comment]
![image.png](https://images.zenhubusercontent.com/623a3fd7095b23600bfd79ce/94aaf936-6e28-40fc-a148-87af0108816b)

Botão suporte no footer, segue XD:
https://xd.adobe.com/view/f6057092-e218-47ab-986c-6903c7b500f7-a356/

Quando em hover usar o azul UNICEF #1CABE2 com fonte no branco.

**Comment by mfreireunicef** [comment]
Apontar para o seguinte link: https://forms.gle/YTZr4K4CAHc2A7EW9
