### ISSUE TITLE
[EXLUIR] Barra de projeção dos IS(Indicadores Sociais)

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#428]
**Descrição:** Excluir a barra de PROJECÃO dos Indicadores Sociais.

![Captura de Tela 2022-12-05 às 12.31.58.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/49d096a9-1cad-4b3b-a846-f0ac499da259)

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef apás analise, verifiquei que não existe alteração de front nessa demanda, basta apenas o back-end nao enviar a projeção que o front não vai rederizar.
