### ISSUE TITLE
[ADICIONAR ATIVIDADES - RS 1] Plano Municipal pela primeira infancia

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#431]
**Description**: Atividade - Plano Municipal da Primeira Infância - 2022

Regras de Pontuação (Atividade):

O Município pontua 2 pontos se e somente se entregar a "Atividade completa" dentro do prazo.
Caso a entrega seja realizada após o prazo estabelecido , o Município pontua 1 ponto.
Caso não atendam aos critério acima, não haverá pontuação.

Links úteis:

[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

[Responsivo - referência ](https://xd.adobe.com/view/3c95ad06-7ecb-4c4d-90d8-0901ffb6c3db-69c6/grid)

Source: PCJ
Título: Atividade - Plano Municipal da Primeira Infância - 2022
Prazo: 31/03/2023

![Captura de Tela 2022-12-12 às 19.54.14.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/a5b6081b-1843-46ea-bf6a-aa0f94fdc5ba)

**Comment by fialalucas** [comment]
https://xd.adobe.com/view/b7333c87-a717-4d3b-866c-7a75116bd7bc-e260/
