### ISSUE TITLE
[FORMACÃO] DIVIDIR FORMACÃO RS 3 EM DUAS 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#433]
Description: Dividir a seguinte formacão do RS 3 em duas conforme descritivo abaixo:

**Segunda Formação**

**Título**: Formação 2
Descritivo: Apresentar certificados das capacitações em água, saneamento e promoção de higiene nas escolas e unidades de saúde para a prevenção e controle da Covid-19 de, no mínimo, 1 servidor público da área de educação, 1 da área de saúde e 1 da área de assistência social.

**Nome do curso:** 
![Captura de Tela 2022-12-23 às 10.13.17.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/e9797a6f-bf4a-4d30-b578-d69b679b54f9)

**Regra de pontuação**: Pelo menos 3 profissionais, independente do cargo, realizando o curso. **(IGNORANDO A CATEGORIA DO CURSO)**

**Prazo:** 13/01/2023

![Captura de Tela 2022-12-12 às 20.16.12.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/bf373fdf-5204-4dfd-a776-c3c91ede860f)

**Comment by fialalucas** [comment]
https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/
