### ISSUE TITLE
[ALTERAR PRAZO e TÍTULO] RS 5 - Atividade Apoio Psicosocial

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#436]
Description:
- Alterar TÍTULO da atividade de: **"Apoio Psicossocial"**, para: **“Serviço de Apoio Psicossocial Criado no Município”** 
- **Prazo:** 13/01/2023

**Comment by mfreireunicef** [comment]
@fialalucas @lucasferreiraunicef prazo e prototipo

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

Conforme tela abaixo, o título está incorreto:

![Captura de Tela 2022-12-29 às 08.57.00.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/da306747-137c-45f7-875f-02c4b3ba2fd1)

Título correto: “Serviço de Apoio Psicossocial Criado no Município”

**Comment by mfreireunicef** [comment]
@fialalucas Conforme informado, segui o UX da pagina  

![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/bc168a3d-f926-467a-9f15-62a56eec9e78)

![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/2ec49f6e-a302-4798-b586-f4ec06528455)
