### ISSUE TITLE
[ALTERAR PRAZO e TÍTULO] RS 6 - Atividade Ações de prevenção contra Violência

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#438]
Description: 
- Alterar TÍTULO da atividade de: **"Ações de prevenção contra Violência"**, para: **“5 Ações e/ou Campanhas de Prevenção e Resposta às Violências”**

**Prazo**: 13/01/2023

**Comment by mfreireunicef** [comment]
@fialalucas prototipo

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

Conforme tela abaixo, o título está incorreto.
![Captura de Tela 2022-12-29 às 08.54.53.png]
(https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/0e3141e4-90bf-4ee5-99b4-d1e41ff2de85)

Título correto: “5 Ações e/ou Campanhas de Prevenção e Resposta às Violências”

**Comment by mfreireunicef** [comment]
@fialalucas Conforme informado, segui o UX da pagina 

![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/e0a770ff-78b4-46b7-a7a8-30f47887c210)
![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/2ec49f6e-a302-4798-b586-f4ec06528455)
