### ISSUE TITLE
[ERROS DE PONTUACÃO] Verificar erros de pontuacão nos resultados sistêmicos *

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#440]
Description: Verificar as regras de pontuacão dos resultados sistêmicos.

Exemplo: Município de Acaraú - CE, Resultado Sistêmico 3 -> Este RS está como "ATRASO" mas nenhuma atividade listada neste resultado sistêmico está como atrasada.

**REGRA:**

**A data do último CARD deve ser a data da tela.**

**Comment by mfreireunicef** [comment]
@fialalucas @lucasferreiraunicef preciso do prazo da pagina (ou regra de prazo) para controle do componente de prazo. Alem disso, os pontos do componente é que definem se esta concluido fora do prazo (ponto: 1) e concluido no prazo (pontos: 2)
