### ISSUE TITLE
[ALTERAR PRAZO e TÍTULO] Atividades: "O funcionamento regular do CMDCA" & "O funcionamento regular do Conselho Tutelar"

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#441]
Description: Alterar PRAZO e TÍTULO das seguintes atividades abaixo:

Atividade: "O funcionamento regular do CMDCA"
Alterar para: "Reunião do CMDCA de Acompanhamento e Avaliação do Plano de Ação Municipal"
Prazo: 30/06/2024

Sub atividades 1
Alterar título para: "Atividade 1 - Reunião CMDCA - 2022"

Sub Atividade 2
Alterar título para:  "Atividade 2 - Reunião CMDCA - 2023"

____________________________________________________________________________________________

Atividade: "O funcionamento regular do Conselho Tutelar"
Alterar para: "Funcionamento Regular do Conselho Tutelar"
Prazo: 30/06/2024

**Comment by fialalucas** [comment]
https://xd.adobe.com/view/1b130628-74a2-492f-8407-2f0629cb5e64-4e40/

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

A data continua incorreta, segue abaixo:

![Captura de Tela 2022-12-29 às 08.53.04.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/c7e0de2d-ac1d-49b9-b1f1-f68bc769a4af)

Prazo correto: 30/06/2024

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef a planilha que me foi passado para alterar todas as datas, a data consta essa

![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/1c0092a9-1c59-469a-a546-6357f9526c38)

segue card com a planilha: https://app.zenhub.com/workspaces/paineis-do-selo-62326e8ea3709300103bf0a0/issues/gh/unicef01/paineis-do-selo/442
