### ISSUE TITLE
[ALTERAR PRAZOS] 

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#442]
**Description:** Alterar os prazos de atividades que estiverem DESATUALIZADAS no painel.

**Lista de atividades (Prazo):**

**Atividade:**
**Prazo ->** De: xx/xx/xx  Para: xx/xx/xx

**Comment by fialalucas** [comment]
https://unicef-my.sharepoint.com/:x:/g/personal/lfiala_unicef_org/EWkv7CFnA4JAvrNQnissJSMBsGrGFW_vynAW9hdV4kDrgA?e=eXmwyN
