### ISSUE TITLE
[STATUS RESULTADO SISTÊMICO]

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#464]
Description: Efetuar a alteracão dos Status atuais apresentados em tela.

Referência:
![Captura de Tela 2022-12-20 às 15.43.27.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/5f694638-ee4b-43cb-9262-8a7f25943ea7)

Alterar **DE:**

Em progresso
Em atraso
Concluido fora do prazo
Concluido dentro do prazo

**PARA:**

Sem pontuação:

“Atividade(s) em progresso”

Pontuação 0:

“Atividade(s) não concluída(s)”
 
Pontuação 1:

“Atividade(s) concluída(s) fora do prazo”

Pontuação 2:

“Atividades concluídas dentro do prazo”

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

Precisa seguir a relacão abaixo:

Sem pontuação:

“Atividade(s) em progresso”

Pontuação 0:

“Atividade(s) não concluída(s)”

Pontuação 1:

“Atividade(s) concluída(s) fora do prazo”

Pontuação 2:

“Atividades concluídas dentro do prazo”

Continua como "PONTUACÃO EM PROGRESSO", portanto, continuar "errado".
![Captura de Tela 2022-12-29 às 08.50.04.png](https://images.zenhubusercontent.com/6239dbfdd8cc266a1b2acd2e/89cb7ea7-552c-4d1e-aaa4-84d3785c78b4)

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Resolvido
 ![image.png](https://images.zenhubusercontent.com/6297ef9962acdd7a2aa9080d/96804089-868b-48c1-bff4-264e6dab22c9)
