### ISSUE TITLE
Revisão de texto

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#527]
**Description:** Efetuar os ajustes de texto e componentes conforme protótipos abaixo.

**Reposicionar**
Reposicionar os cards dos RS de acordo com a data de vencimento

**Home:** https://xd.adobe.com/view/23e40b46-1fb9-43f2-b712-b175d624374c-76b7/

Texto do map-data-title;
Texto do map-data-subtext
Textos e diagramação dos cards com números

**Resumo:** https://xd.adobe.com/view/a6825c30-d576-4eb8-8e4e-e1fb56b323f9-f3d1/specs/

Texto resumo
Textos e cards de Participação Cidadã
Textos de Resultados Sistêmicos
Cards de resultados sistêmicos

**RS1:** https://xd.adobe.com/view/6532bd59-5ee4-46e1-8448-31862cd922bb-3061/ (inclui links das atividades)

**Demais RS + Participação Cidadã e Gestão por Resultados:** 
RS + Participação Cidadã.docx  (inclui links dos cards)

[RS + Participação Cidadã (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGtuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7bd37e749905bc2dcbf9d306b652c63f9657542f/RS%20%2B%20Participac%CC%A7a%CC%83o%20Cidada%CC%83%20%281%29.pdf)

**Alterações de layout para RS's:** https://xd.adobe.com/view/f01fd193-6022-4d0d-95f3-d68fd9af7506-a54c/

- Excluir PNG de "Município participante do Selo"
- Diminuir quantidade de texto da descrição da RS (180 caracteres ou 3 linhas ou 30 palavras);
- Colocar ODS's dentro do "LER MAIS" abaixo do texto de descrição da RS.
- Alterar margens das divs para que parte das atividades já apareçam no primeiro scroll.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef @dlazaroni Não entendi o item "Alterações de layout para RS's: layout-RS.png", por favor, disponibilizar XD de TODOS os RS com suas respectivas alteracões de layout que serão feitas, para assim evitar retrabalho ou interpretacão errônea.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef o item: 
"Reposicionar
Reposicionar os cards dos RS de acordo com a data de vencimento"

Ja havia sido abordado anteriormente e ficou acordado que isso teria que ser repensado, pois SEMPRE está sendo necessário mudar datas (prolongar principalmente) e com isso teriamos que ficar sempre reorganizando a estrutura da página e a mesma foi definida/pensada por duas vezes que a posicão dos cards seriam FIXAS NA TELA (tanto na versão inicial quanto na segunda versão do SELO, a versão refatorada) .

**Comment by dlazaroni** [comment]
@mfreireunicef alterei a descrição do épico e inclui o XD do template de RS com as alterações solicitadas

**Comment by mfreireunicef** [comment]
Conferido @dlazaroni , obrigado pelo apoio.

**Comment by mfreireunicef** [comment]
@dlazaroni @lucasferreiraunicef  preciso desse XD do RESUMO liberado, textos e SVG para que eu possa aplicar.

https://xd.adobe.com/view/a6825c30-d576-4eb8-8e4e-e1fb56b323f9-f3d1/

exemplo SVG:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU5EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66ceed9cf789616132b23aa2a558ed8312a6f128/Captura%20de%20Tela%202023-08-28%20a%CC%80s%2012.44.06.png)

Alem disso, conforme solicitadao na daily, aguardo atualização da tela do RS1 (textos, SVG e diferença de cards).

**Comment by dlazaroni** [comment]
@mfreireunicef 
1) Segue o link do XD com os SVGs para download: https://xd.adobe.com/view/a6825c30-d576-4eb8-8e4e-e1fb56b323f9-f3d1/specs/

2) Textos do RS1 adicionados ao DOC: https://unicef-my.sharepoint.com/:w:/g/personal/dlazaroni_unicef_org/EXA8zEoYnuFOnxIxWPJEmpQBgfK9n37ol298rf7tO_d8iA?ovuser=77410195-14e1-4fb8-904b-ab1892023667%2Cdlazaroni%40unicef.org&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIxNDE1LzIzMDcwMzA3MzQ2IiwiSGFzRmVkZXJhdGVkVXNlciI6ZmFsc2V9

**Comment by mfreireunicef** [comment]
@dlazaroni não to conseguindo acessar o "Textos do RS1 adicionados ao DOC..." poderia enviar?

**Comment by mfreireunicef** [comment]
@dlazaroni Obrigado.
