### ISSUE TITLE
Pontuacão Pagina de RESUMO

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#588]
Description: Pontuacão 

Pontuacão Resumo deve seguir a nova regra aplicada a PONTUACÃO GERAL do Resultado Sistêmico.
<img width="117" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65b9d8deb437514126c31140484a68ea0af7e916/Captura%20de%20Tela%202023-12-11%20a%CC%80s%2015.00.13.png" alt="Captura de Tela 2023-12-11 às 15.00.13.png" />

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Não consegui entender a demanda. Hoje o resumo ja segue a pontuação geral do card a diferença é que o card a pontuação so será exibida depois de 30/06/2024.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Não consegui entender a demanda. Hoje o resumo ja segue a pontuação geral do card a diferença é que o card a pontuação so será exibida depois de 30/06/2024.

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef Não consegui entender a demanda. Hoje o resumo ja segue a pontuação geral do card a diferença é que o card a pontuação so será exibida depois de 30/06/2024.

**Comment by mfreireunicef** [comment]
Essa demanda se resolve quando a demandaa baixo for finalizada:
https://app.zenhub.com/workspaces/paineis-do-selo-62326e8ea3709300103bf0a0/issues/gh/unicef01/paineis-do-selo/587
