### ISSUE TITLE
Alterar TEXTO Card BAV

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#615]
**Alterar texto:**

**DE** "Cadastro da equipe na plataforma da BAV: Gestor(a) da Política Pública Municipal, Coordenador(a) Operacional Municipal, Supervisores Institucionais da Saúde, Educação e Assistência Social, Técnicas(os) Verificadoras(es) e Agentes de Alertas."  **PARA** "Adesão do Prefeito à estratégia BAV realizada pela plataforma".

O card ficaria assim:

<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9267de5d8e40d37a409536be20b07133a54886aa/image.png" alt="image.png" />

**Comment by dlazaroni** [comment]
@gucostaunicef @lucasferreiraunicef validado
