### ISSUE TITLE
[Homologação] RS1 - BAV

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#635]
Validação de dados cruzando base original + status do card no painel para 3 municípios.

- [ ] Anexar print com evidências.
- [ ] Verificar links das atividades do card
- [ ] Verificar prazo

<img width="323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTF0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11c1ad98428380f5e817d65621f97b61b2351b25/image.png" alt="image.png" />

https://unicef-my.sharepoint.com/:x:/r/personal/dlazaroni_unicef_org/_layouts/15/Doc.aspx?sourcedoc=%7BC79D7929-A69B-4584-8E81-1133109D6B4F%7D&file=Versionamento%20Atividades%20Pain%C3%A9is%20do%20SELO%20-%202024.xlsx&action=default&mobileredirect=true

**Comment by gucostaunicef** [comment]
<img width="1948" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEY4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cd6951b38054158ac322799987d512d5a56eb1a/acrelandia-ava.png" alt="acrelandia-ava.png" />
<img width="1087" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME44QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cddadc470ba94d71a0035300941861f1be08b37f/acrelandia-bav.png" alt="acrelandia-bav.png" />
<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFI4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18bee173a898d8b2fffdc75abe2ff8ace834fb8/acrelandia-painel.png" alt="acrelandia-painel.png" />
<img width="1966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFY4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d762c43bf580eaa8f4656ed9da2df63081d703f6/cg-ava.png" alt="cg-ava.png" />
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFo4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ddb3531f14aa66f3f79ac69b7548d59bce3819a/cg-bav.png" alt="cg-bav.png" />
<img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2100b59e1176729305019d9803485d40424cda91/cg-painel.png" alt="cg-painel.png" />
<img width="1958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGg4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176ec6096015231de40ff9cd745b9be5c725a746/sobral-ava.png" alt="sobral-ava.png" />
<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGw4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--524a3faefca63be0e9c8a4d3b6730648f65c4678/sobral-bav.png" alt="sobral-bav.png" />
<img width="471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50eb640896b9645ddc2ebd6c037b094b0ab6fe79/sobral-painel.png" alt="sobral-painel.png" />
