### ISSUE TITLE
[Homologação] RS1 - Profissionais certificados em pelo menos 1 dos 4 cursos sobre Educação Infantil

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#639]
Validação de dados cruzando base original + status do card no painel para 3 municípios (Sobral/CE , Campina Grande/PB, Acrelandia/AC).

 

- [ ] Anexar print com evidências.
- [ ]  Verificar links das atividades do card
- [ ]  Verificar prazo

<img width="555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTl5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b461f7dc3d7d76e5f8897b574c3704ce0c2ead3f/image.png" alt="image.png" />

**Comment by gucostaunicef** [comment]
Acrelândia:
<img width="907" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa01508350545c7682b179830feaa601fbb5a63a/acrelandia-ava.png" alt="acrelandia-ava.png" />
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb7b700c1191d8034f3933b2f7ee952729fba994/acrelandia-painel.png" alt="acrelandia-painel.png" />


Campina Grande:
<img width="965" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--165ff3ae12d83c68d64b66b786ec4ba219b152f7/cg-ava.png" alt="cg-ava.png" />
<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWlSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23eed77f61c451ae3b7fcb85a6781a745caf7bf1/cg-painel.png" alt="cg-painel.png" />


Sobral:
<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1SQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c154251c32ebc19dccb1454c54388de08bd3708e/sobral-ava.png" alt="sobral-ava.png" />
<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--777cc9222d8cecc618cab7b5508cf5c27c8830ef/sobral-painel.png" alt="sobral-painel.png" />
