### ISSUE TITLE
[Homologação] RS1 - INDIQUE: autoavaliação da qualidade das Unidades de Educação Infantil (2ª medição - 2024)

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#642]
Validação de dados cruzando base original + status do card no painel para 3 municípios (Sobral/CE , Campina Grande/PB, Acrelandia/AC).

 

- [ ] Anexar print com evidências.
- [ ]  Verificar links das atividades do card
- [ ]  Verificar prazo

<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk55QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a5de1f8d8143a8c8c6972204f568a05b071f436/image.png" alt="image.png" />

**Comment by lucasferreiraunicef** [comment]
@dlazaroni **Segue compilado de resultados relacionados a PESQUISAS.**

[Monitoramento de resultados relacionados às entregas no site de pesquisas do UNICEF.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a89488e7f56efe82397bb07bd09ba248cdf3dca5/Monitoramento%20de%20resultados%20relacionados%20a%CC%80s%20entregas%20no%20site%20de%20pesquisas%20do%20UNICEF.docx)
