### ISSUE TITLE
[Homologação - PCJ] RS1 - Elaboração do Plano Municipal pela Primeira Infância - (PMPI) implementado

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#644]
Validação de dados cruzando base original + status do card no painel para 3 municípios (Sobral/CE , Campina Grande/PB, Acrelandia/AC).

 

- [ ] Anexar print com evidências.
- [ ]  Verificar links das atividades do card
- [ ]  Verificar prazo

<img width="648" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmR5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4e34aaab0d8759f22de9554f735077636725bf2/image.png" alt="image.png" />

**Comment by gucostaunicef** [comment]
Acrelândia:

<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHQvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfc5a4ebd50ba5ac9427196871758e2cfc1f151c/acrelandia-painel.png" alt="acrelandia-painel.png" />
<img width="1698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHgvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37f4c851b7100b17c10cc776452e2a2a0a547133/acrelandia-pesquisas.png" alt="acrelandia-pesquisas.png" />

Campina Grande:
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODEvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a6898e6a2d4e7247960508d199e50a6568c6d19/cg-painel.png" alt="cg-painel.png" />
<img width="1786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODUvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e79d1afbd503935d49e9910fb5e6b831a3d268fd/cg-pesquisas.png" alt="cg-pesquisas.png" />


Sobral:
<img width="695" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODkvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26ccf598666c5b487aedbcf41cc0b756c28c7912/sobral-painel.png" alt="sobral-painel.png" />
<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUIvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e427d7488b3dfc053f1824514d2aeeb110cedcf1/sobral-pesquisas.png" alt="sobral-pesquisas.png" />
