### ISSUE TITLE
[Homologação] RS2 - AVA - Profissionais certificados nos cursos Gestão Escolar e Professores na Rede ou Gestão Educacional na Rede

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#656]
Validação de dados cruzando base original + status do card no painel para 3 municípios (Sobral/CE , Campina Grande/PB, Acrelandia/AC).

 Cursos id=23 e id=18

- [ ] Anexar print com evidências.
- [ ]  Verificar links das atividades do card
- [ ]  Verificar prazo

<img width="505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85dcd95218956b9c58575e21cf8b78248548ddf5/image.png" alt="image.png" />

**Comment by gucostaunicef** [comment]
**Acrelândia:**
<img width="1098" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0c2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33220a7d3c53ac158bfb7431c5a32e209e0fa04e/acrelandia-ava.png" alt="acrelandia-ava.png" />
<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0s2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--371bd33b40837f20bae1a2ddc3970ffa76b5ab13/acrelandia-ava-2.png" alt="acrelandia-ava-2.png" />
<img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd082QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--204f5a54208358e84ae61b43145619ff7a0d462a/acrelandia-painel.png" alt="acrelandia-painel.png" />

**Campina Grande:**
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1M2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--465bcc88e72bca0a6fd52f2c68be65ed4c92bf26/cg-ava.png" alt="cg-ava.png" />

<img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1c2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2a6e99cb59bbaf02c95d13804e5816f2649c93a/cg-ava-2.png" alt="cg-ava-2.png" />
<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2U2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff92e282d1a31559b6b31e8e1fdf191370b90153/cg-painel.png" alt="cg-painel.png" />

**Sobral:**
<img width="984" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2k2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9bdaf48e6c86d5cb344c379376dc12b89cffe86/sobral-ava.png" alt="sobral-ava.png" />
<img width="1228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd202QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edaf278b3c138b6aa4d1e38243fe2d932acc2eaa/sobral-ava-2.png" alt="sobral-ava-2.png" />
<img width="507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3E2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de2a7952a6ac0917872765854e86a6ccf2038b83/sobral-painel.png" alt="sobral-painel.png" />
