### ISSUE TITLE
[Homologação] RS2 - AVA - Profissionais certificados no curso Práticas de Alfabetização em Contextos de Multiletramentos

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#657]
Validação de dados cruzando base original + status do card no painel para 3 municípios (Sobral/CE , Campina Grande/PB, Acrelandia/AC).

 Curso id=24

- [ ] Anexar print com evidências.
- [ ]  Verificar links das atividades do card
- [ ]  Verificar prazo

<img width="477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21MQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfccd25655c16dc21647c1a099c191a11b73d72d/image.png" alt="image.png" />

<img width="492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99c7304e54bca676a703cf44a13634d66ac254c6/image.png" alt="image.png" />

**Comment by gucostaunicef** [comment]
Acrelândia:
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0dmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8fe736073af00ac1b4737ddaf8832c15bab5c25/acrelandia-ava.png" alt="acrelandia-ava.png" />
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7b8a38b593c55bb73edc07accb31e13ec3c9920/acrelandia-painel.png" alt="acrelandia-painel.png" />

Campina Grande:
<img width="1641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ae525222cf55e8b2e1ac68c6bfa386af3705c88/cg-ava.png" alt="cg-ava.png" />
<img width="573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1dmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e4046c163ca5fa523a9f475d324d4fe76964ad9/cg-painel.png" alt="cg-painel.png" />

Sobral:
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2FmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--168b90dc3106d95301c358b0cf90d7fa441facd4/sobral-ava.png" alt="sobral-ava.png" />
<img width="556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3e194fa7a79c20dccdb84d77abc11269f8ec4b4/sobral-painel.png" alt="sobral-painel.png" />
