### ISSUE TITLE
URLs SELO

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#702]
- Precisamos que na hora que alterar o filtro, altere a url com query string para o usuario poder compartilhar sem precisar de filtrar tudo novamente
- Precisaremos que esses valores da querystring também esteja em uma tag html dentro do componente de embed para conseguirmos também alterar a url do Portal, ou seja, sempre que alterar o filtro, troca também na url do portal Selo. Faremos isso com um JS que ira ficar observando um field oculto dentro do wireframe com evento de change.

sempre passar na URL o ?city_id
alem do embeve aplica sintaxe do município
UF_nome-do-municipio 
Exemplo:
RN_sao-jose-do-serido
BA_barreiras

https://paineis.selounicef.org.br/resumo?uf=UF&cidade=nome-da-cidade
https://paineis.selounicef.org.br/participacao-cidada?uf=UF&cidade=nome-da-cidade
https://paineis.selounicef.org.br/resultados-sistemicos-01?uf=UF&cidade=nome-da-cidade
https://paineis.selounicef.org.br/indicadores-sociais?uf=UF&cidade=nome-da-cidade

**Comment by mfreireunicef** [comment]
Fiz uma alteracao no modelo de URL para seguir o padra do SELO que sempre referencia o municipio:
https://paineis.selounicef.org.br/resumo?uf=UF&municipio=nome-da-cidade

**Comment by mfreireunicef** [comment]
Fiz uma alteracao no modelo de URL para seguir o padra do SELO que sempre referencia o municipio:
https://paineis.selounicef.org.br/resumo?uf=UF&municipio=nome-da-cidade
