### ISSUE TITLE
API 1MiO - qtde de oportunidades

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#703]
Oi, @Guilherme, conferi no banco e puxei via API também, e para mim o valor de municípios que criaram as oportunidades com base nas regras é de 658, ou seja, uma diferença de 3 com o número que você informou.

Acredito que isso possa ser algum município com o mesmo nome em diferentes estados que ainda não estejam em sua lista de homônimos.

Vou deixar aqui o link do retorno que tive da API para vocês compararem e identificarem quais esses 3 municípios.
https://docs.google.com/spreadsheets/d/1-R4cPYpfPSWP5I4iSmKuMkTTzHiIrdoV54TKTNqLAFc/edit?usp=sharing

**Comment by gucostaunicef** [comment]
Municípios que apareceram na divergência:

1. Queimadas - OK: Problema de homônimo
2. Trindade/PE: População de 30816 e criou apenas 10 oportunidades (deveria ser no mínimo 15)
3. Santa Cruz/PB: Cadastro de telefone errado (99) 99999-9999
