### ISSUE TITLE
RS1 - Flexibilização AVA Educação

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#705]
No RS1, card **Profissionais certificados em pelo menos 1 dos 4 cursos sobre Educação Infantil**

- Remover bullets (checks);
- Alterar descrição
- Remover regra de negócio que considere o perfil do usuário. Agora pode ser qualquer usuário com qualquer perfil.
- Incluir módulo de "X/3" com o quantitativo de concluíntes, conforme print: <img width="108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3QrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7d4f1666a7fc83055c7e97562968a61755a40a0/image.png" alt="image.png" />

DE:
<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzU5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e959cfce31c8f554576e8dd798a7af66c7c6044b/image.png" alt="image.png" />

PARA:
<img width="422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzk5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69cac1995bb12976e0d17951b02e5953f079de80/image.png" alt="image.png" />

Texto da descrição: 
3 profissionais concluindo um dos 4 cursos disponíveis sobre Educação Infantil (Práticas de Qualidade na Educação Infantil; Espaços, materiais, tempos e relações de qualidade na Educação Infantil; Gestão de Qualidade na Educação Infantil; Avaliação do atendimento na Educação Infantil)

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef
