### ISSUE TITLE
RS2 - Flexibilização AVA Educação

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#706]
No RS2, cards **Profissionais certificados nos cursos Gestão Escolar e Professores na Rede ou Gestão Educacional na Rede** e **Profissionais certificados no curso Práticas de Alfabetização em Contextos de Multiletramentos**

- Não serão mais dois cards, esses cards vão virar apenas um card;
- Remover bullets (checks);
- No novo e único card: Alterar título e descrição
- Remover regra de negócio que considere o perfil do usuário. Agora pode ser qualquer usuário com qualquer perfil.
- Adicionar 5 botões para linkar para os cursos (títulos e links dos 5 cursos listados abaixo)
- Incluir módulo de "X/3" com o quantitativo de concluíntes, conforme print: <img width="108" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3QrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7d4f1666a7fc83055c7e97562968a61755a40a0/image.png" alt="image.png" />

DE:
<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEIrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc6722b756118288992c0daf818869e704726994/image.png" alt="image.png" />

PARA:
<img width="321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEYrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--622217125a1a1bb7a406045214b3e5c55618c081/image.png" alt="image.png" />

**Título do card:**
Profissionais certificados em pelo menos 1 dos 5 cursos sobre Ensino Fundamental

**Texto da descrição:** 
3 profissionais concluindo um dos 5 cursos disponíveis sobre Ensino Fundamental (Práticas de Alfabetização em Contexto de Multiletramentos; Gestão Escolar e Professores na Rede; Gestão Educacional na Rede; Currículo Integrado; Desenvolvimento de Competência para o Enfrentamento da Cultura do Fracasso Escolar)

**Títulos e links dos cursos:**
Práticas de alfabetização em contexto de multiletramentos - https://ava.unicef.org.br/course/view.php?id=24
Gestão escolar e professores na rede: políticas para o sucesso escolar - https://ava.unicef.org.br/course/view.php?id=23
Gestão educacional na rede: políticas para o sucesso escolar - https://ava.unicef.org.br/course/view.php?id=18
Currículo integrado - https://ava.unicef.org.br/course/view.php?id=91
Desenvolvimento de competência para o enfrentamento da cultura do fracasso escolar - https://ava.unicef.org.br/course/view.php?id=45

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef
