### ISSUE TITLE
Embed Painel - URL definitiva

### ISSUE THREAD

**Issue by dlazaroni** [UNICEF01/Paineis-do-Selo#723]
Alterar URL https://paineis.testes.selounicef.org.br/ para https://paineis.embed.selounicef.org.br/

1) Criar sub-domínio **(feito)**
2) Adicionar menu (fora do header)
3) Atualizar ambiente de testes **(feito)**

**Comment by mfreireunicef** [comment]
Item 2 ja na branch "homolog".
