### ISSUE TITLE
[RS3]  Adicionando botão "Abrir Atividade" com link nos cards quando o card estiver com status 'Em progresso' 

### ISSUE THREAD

**Issue by mfreireunicef** [UNICEF01/Paineis-do-Selo#87]
Link para as atividades (RS 3):

[Abrir atitivade]( https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/screen/48b5d0c4-09aa-41d1-9dd1-544990469c54/specs/)

**Comment by mfreireunicef** [comment]
PR: https://github.com/UNICEF01/Paineis-Selo-UNICEF-front/pull/8

**Comment by mfreireunicef** [comment]
@lucasferreiraunicef por favor inserir aqui os links  dos cards da tela 7 da RS3 para serem abertos no nos botões "Abrir Atividades"

XD: https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/screen/48b5d0c4-09aa-41d1-9dd1-544990469c54/specs/

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef 

Card autoavaliacão sanitária:
(Pesquisas BAE)
https://pesquisas.buscaativaescolar.org.br/

Card Protocolos da Covid-19:
(Pesquisas BAE)
https://pesquisas.buscaativaescolar.org.br/

Card Formação:
(Moodle)
https://ava.unicef.org.br/login/index.php

**Comment by mfreireunicef** [comment]
https://github.com/UNICEF01/Paineis-Selo-UNICEF-front/pull/9
