### ISSUE TITLE
[RS3] Rework do componente de pontuação da RS conforme novo modelo do link (alterar componenete)

### ISSUE THREAD

**Issue by mfreireunicef** [UNICEF01/Paineis-do-Selo#93]
Link: https://xd.adobe.com/view/c6c4c882-6fa1-40b3-9832-a88ea0b7369e-9397/specs/

Obs.: Ficou acordado em reunião(09/06) com o @fialalucas e @lucasferreiraunicef que nesse primeiro momento não seria viável inserir o texto "Atividade x - StatusAtividade" nos cards, nem inserir o  texto "Em progresso Prazo das atividades 1, 2 e 3 expiram em xx dias" na Pontuação. Isso será revisto e discutido mais para frente.

**Comment by mfreireunicef** [comment]
PR: https://github.com/UNICEF01/Paineis-Selo-UNICEF-front/pull/8

**Comment by mfreireunicef** [comment]
Optei para que no status "em progresso" se mantivesse o padrão dos demais status (exibindo a pontuação).  Também optei por não adicionar a cor CINZA no status "em progresso", pois nesse momento seria uma lógica extra (levando em consideração o prazo do projeto) e sairia do padrão no contexto geral da tela, já que o status "em progresso" é sempre representado pela cor AMARELA(ex.: cards).

**Comment by mfreireunicef** [comment]
PR: UNICEF01/Paineis-Selo-UNICEF-front#8

**Comment by lucasferreiraunicef** [comment]
@mfreireunicef ao longo da semana, vou inserir essa atividade no Backlog. Aproveitando, explicando o porquê de não termos o BACKLOG inteiro mapeado: O SELO é o projeto que possui a maior suscetibilidade de alterar sua regra de negócio a qualquer momento do dia ou do processo. Logo, teríamos que alterar todo o backlog quase que diariamente, seria oneroso. Estou satisfeito com sua análise das correções, obrigado.
